// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

/*---------------------------------------------------------------
 * Generated UI state
 * SquareLine uses this object for project-level initial actions.
 *--------------------------------------------------------------*/

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

/**
 * @brief Create the generated screen and make it visible.
 *
 * setup() calls this function after the PlatformIO display and input devices
 * are ready. It applies the theme, builds Screen1, and loads it.
 *
 * @param None.
 * @return Nothing.
 */
void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}

/**
 * @brief Delete all objects created by the generated UI.
 *
 * The current application keeps Screen1 for its whole lifetime; call this
 * function before rebuilding or replacing the screen.
 *
 * @param None.
 * @return Nothing.
 */
void ui_destroy(void)
{
    ui_Screen1_screen_destroy();
}
